DEBUG    [2021-05-21 00:14:58,402] asyncio.__init__(623): Using proactor: IocpProactor - extra: {'name': 'asyncio', 'msg': 'Using proactor: %s', 'args': ('IocpProactor',), 'levelname': 'DEBUG', 'levelno': 10, 'pathname': 'C:\\Program Files\\Python39\\lib\\asyncio\\proactor_events.py', 'filename': 'proactor_events.py', 'module': 'proactor_events', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 623, 'funcName': '__init__', 'created': 1621545298.402821, 'msecs': 402.8210639953613, 'relativeCreated': 443.666934967041, 'thread': 3892, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 19676, 'message': 'Using proactor: IocpProactor', 'asctime': '2021-05-21 00:14:58,402'}
