class LogInError(Exception):
    """Error during authorization"""
